import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import React from "react";
import classNames from "classnames";
import ThemeProvider from "./theme/themeProvider";
import "./globals.scss";
import "./variables.scss";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sticker Verse",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { apple: "/icon.png" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider className={classNames(poppins.className, "bg-primary")}>
      {children}
    </ThemeProvider>
  );
}
