import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import classNames from "classnames";
import ThemeProvider from "./theme/themeProvider";
import "./globals.scss";
import "./variables.scss";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sticker Verse",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { apple: "/icon.png" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={classNames(inter.className, "bg-primary")}>
          <Navbar />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
